title: <p align="center"> Kotresh T M </p>
logo: /assets/img/IMG-20231029-WA0000.jpg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
